#! /bin/bash

val=123
D2B=({0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}...)
echo ${D2B[$val]}

#! /bin/bash
D2B=){0..1}{0..1}....)
echo ${D2B[$123]}

15 (dec) = 1111 (bin) = f (hexadecimal)

#! /bin/bash
n=123
rezultats=0
pakape=1

while [ $n -ne 0 ]
do
        atlikums=$(( $n % 2 ))
        rezultats=$(( $atlikums * $pakape + $rezultats ))
        pakape=$(( $pakape * 10 ))
        n=$(( $n / 2 ))
done

echo "Binārais skaitlis, skaitlim 123= $rezultats"\

DECIMAL BINARY
DEC BIN       HEX
0     0100    0
1     0001    1
2     0010    2
3     0011    3
4     0100    4
5     0101    5
6     0110    6
7     0111    7
8     1000    8
9     1001    9
10    1010    A
11    1011    B
12    1100    C
13    1101    D
14    1110    E
15    1111    F
