#!/bin/bash
git config --global user.email komar112@inbox.lv
git add .
git commit -m "20202107_18_40"
git pull
git push origin master


Example to mpush with Date

#!/bin/bash
if [ $# == 1 ]
then
        git config --global user.email komar112@inbox.lv
        git add .
        git commit -m $1
        git push origin master
fi


Sometimes need add

#!/bin/bash
if [ $# == 1 ]
then
        git config --global user.email komar112@inbox.lv
        git add .
        git commit -m $1
        git pull
        git push origin master
fi
